import * as path from "path"
import type { Manifest, ManifestEntry } from "./ResearchIndexer"

const RECENTLY_MODIFIED_DAYS = 7

function formatDate(ms: number): string {
	return new Date(ms).toISOString().slice(0, 10)
}

function groupByTopDir(files: Record<string, ManifestEntry>, workspacePath: string): Map<string, string[]> {
	const groups = new Map<string, string[]>()
	for (const relPath of Object.keys(files).sort()) {
		const parts = relPath.split(/[\\/]/)
		const topDir = parts.length > 1 ? parts[0] : "(root)"
		if (!groups.has(topDir)) groups.set(topDir, [])
		groups.get(topDir)!.push(relPath)
	}
	return groups
}

function recentlyModified(files: Record<string, ManifestEntry>): Array<[string, ManifestEntry]> {
	const cutoff = Date.now() - RECENTLY_MODIFIED_DAYS * 24 * 60 * 60 * 1000
	return Object.entries(files)
		.filter(([, e]) => e.mtime > cutoff)
		.sort((a, b) => b[1].mtime - a[1].mtime)
		.slice(0, 30)
}

export function formatIndexMd(manifest: Manifest): string {
	const totalFiles = Object.keys(manifest.files).length
	const lastScan = manifest.lastFullScan
		? new Date(manifest.lastFullScan).toISOString().replace("T", " ").slice(0, 19) + " UTC"
		: "never"
	const projectName = manifest.projectName || path.basename(manifest.workspacePath)

	const groups = groupByTopDir(manifest.files, manifest.workspacePath)
	const recent = recentlyModified(manifest.files)

	let out = `# Project Index — ${projectName}
> Auto-generated by GenCoder Research Mode. Last full scan: ${lastScan}.
> Files indexed: ${totalFiles}. To refresh: click "Refresh Index" or run agent in Research Mode.

## How Agents Should Use This File
1. Read this index first before exploring the codebase.
2. Navigate directly to files using the paths listed below.
3. If a feature is listed here, REUSE it — do not rebuild it.
4. If you change code, the index auto-updates within 30 seconds.

## Files by Module
`

	for (const [dir, filePaths] of groups) {
		out += `\n### ${dir}/\n`
		for (const relPath of filePaths) {
			const entry = manifest.files[relPath]
			out += `- \`${relPath}\` (${entry.loc} LOC) — indexed ${formatDate(entry.mtime)}\n`
		}
	}

	if (recent.length > 0) {
		out += `\n## Recently Modified (last ${RECENTLY_MODIFIED_DAYS} days)\n`
		out += `| Date | File | LOC |\n`
		out += `|------|------|-----|\n`
		for (const [relPath, entry] of recent) {
			out += `| ${formatDate(entry.mtime)} | \`${relPath}\` | ${entry.loc} |\n`
		}
	}

	return out
}

export function formatArchitectureMd(manifest: Manifest, techStack: TechStack): string {
	const projectName = manifest.projectName || path.basename(manifest.workspacePath)
	const lastScan = manifest.lastFullScan ? new Date(manifest.lastFullScan).toISOString().slice(0, 10) : "never"

	const topDirs = [
		...new Set(
			Object.keys(manifest.files)
				.map((f) => f.split(/[\\/]/)[0])
				.filter(Boolean),
		),
	].sort()

	let out = `# Architecture Overview — ${projectName}
> Auto-generated by GenCoder Research Mode. Updated: ${lastScan}.

## Tech Stack (auto-detected)
`
	for (const [key, value] of Object.entries(techStack)) {
		if (value) out += `- **${key}**: ${value}\n`
	}

	out += `
## Top-level Layout
`
	for (const dir of topDirs) {
		out += `- \`${dir}/\`\n`
	}

	const totalFiles = Object.keys(manifest.files).length
	const totalLoc = Object.values(manifest.files).reduce((sum, e) => sum + e.loc, 0)
	out += `
## Stats
- Total files indexed: ${totalFiles}
- Total lines of code: ${totalLoc.toLocaleString()}
`

	return out
}

export interface TechStack {
	Language?: string
	Framework?: string
	Build?: string
	Tests?: string
	[key: string]: string | undefined
}
